version: "3.9"

services:
  nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile
    ports:
      - 3000:80
      - 443:443
    volumes:
      - ./wordpress:/var/www/html:delegated
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=wp
      - MYSQL_USER=wp
    volumes:
      - ./mysql:/var/lib/mysql:delegated
  php:
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
      - ./wordpress:/var/www/html:delegated
